baseURL: https://tylerbutler.com/
languageCode: en-us
title: Tyler Butler
author:
  name: Tyler Butler
  website: https://tylerbutler.com/
Paginate: 5
metaDataFormat: yaml
theme: dark_rainbow
disqusShortname: tylerbutlercom
googleAnalytics: "UA-26061862-1"
copyright: 2002-2019 Tyler Butler

permalinks:
  pages: /:slug/
  articles: /:year/:month/:slug/

pygmentsCodefences: true

# enables syntax guessing for code fences without specified language
pygmentsCodefencesGuessSyntax: true

# true use pygments-css or false will color code directly
pygmentsUseClasses: true

enableGitInfo: false
enableRobotsTXT: true
disableKinds: ["404"]
disableHugoGeneratorInject: false

outputs:
  home: ["HTML", "RSS"]

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

taxonomies:
  tag: tags
  series: series

privacy:
  googleAnalytics:
    respectDoNotTrack: true
  instagram:
    disable: true
  speakerDeck:
    disable: true
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true

# sectionPagesMenu: main
menu:
  sidebarmiddle:
    - Name: "feed"
      Identifier: "feed"
      URL: "http://feed.tylerbutler.com/AllPosts"
      Weight: 1
    - Name: "archives"
      Identifier: "archives"
      URL: "/articles/"
      Weight: 2
    - Name: "colophon"
      Identifier: "colophon"
      URL: "/colophon/"
      Weight: 3
  sidebarbottom:
    - Name: twitter
      URL: "https://twitter.com/tylerbutler"
      Weight: 1
    - Name: github
      URL: "https://github.com/tylerbutler"
      Weight: 2
  footer:
    - Name: "all articles"
      Identifier: "archives"
      URL: "/articles/"
      Weight: 1
