baseURL: https://tylerbutler.com/
languageCode: en-us
title: Tyler Butler
author:
  name: Tyler Butler
  website: https://tylerbutler.com/
Paginate: 5
metaDataFormat: yaml
theme: dark_rainbow
disqusShortname: tylerbutlercom
copyright: 2002-2024 Tyler Butler

permalinks:
  pages: /:slug/
  articles: /:year/:month/:slug/

pygmentsCodefences: true

# enables syntax guessing for code fences without specified language
pygmentsCodefencesGuessSyntax: true

# true use pygments-css or false will color code directly
pygmentsUseClasses: true

enableGitInfo: false
enableRobotsTXT: true
disableKinds: ["404"]
disableHugoGeneratorInject: false

markup:
  goldmark:
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

outputs:
  home:
    - html
    - rss

outputFormats:
  rss:
    baseName: feed

taxonomies:
  tag: tags
  series: series

privacy:
  googleAnalytics:
    respectDoNotTrack: true
  instagram:
    disable: true
  speakerDeck:
    disable: true
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true

# sectionPagesMenu: main
menus:
  sidebarmiddle:
    - Name: "feed"
      Identifier: "feed"
      URL: "http://feed.tylerbutler.com/AllPosts"
      Weight: 1
    - Name: "archives"
      Identifier: "archives"
      URL: "/articles/"
      Weight: 2
    - Name: "colophon"
      Identifier: "colophon"
      URL: "/colophon/"
      Weight: 3
  sidebarbottom:
    # - Name: twitter
    #   URL: "https://twitter.com/tylerbutler"
    #   Weight: 1
    - Name: github
      URL: "https://github.com/tylerbutler"
      Weight: 1
  footer:
    - Name: "all articles"
      Identifier: "archives"
      URL: "/articles/"
      Weight: 1
