# Default params
theme:
  bigfoot:
    enabled: yes
  typekit_id: vty2qol
  sharing:
    enabled: no
    size: medium
    services:
      - facebook
  comments:
    enabled: yes
    provider: "disqus"
    account: tylerbutlercom
author:
  name: Tyler Butler
  email: tyler@tylerbutler.com
