---
new_page_extension: md
auto_deploy: false
admin_path: _admin
webhook_url: 
sections:
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
- type: directory
  path: content/articles
  label: Articles
  create: all
  match: "**/*"
- type: directory
  path: content/colophon
  label: Colophon
  create: all
  match: "**/*"
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/png2019
  label: PNG 2019
  create: all
  match: "**/*"
- type: directory
  path: data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml,toml}"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.38.1
  output_directory: public
version: 0.38.1
