---
label: default
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- type: datetime
  name: date
  default: ''
  label: Date
  config:
    date_format: YYYY-MM-DD
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
pages:
- content/articles/ten-of-my-favorite-poems.md
